/* eslint-disable no-console */
// Generates src/environments/environment.prod.ts from environment variables so
// the production build points at the deployed backend + Supabase. Runs as the
// `prebuild` npm script (so `npm run build` always regenerates it first).
//
// Render env vars consumed: API_BASE_URL, SUPABASE_URL, SUPABASE_ANON_KEY.
// When a variable is unset, the current value in environment.ts is kept as the
// default, so a plain local `npm run build` produces no change.

const fs = require('fs');
const path = require('path');

const envDir = path.join(__dirname, '..', 'src', 'environments');
const devFile = path.join(envDir, 'environment.ts');
const prodFile = path.join(envDir, 'environment.prod.ts');

function fromDev(key, fallback) {
  try {
    const src = fs.readFileSync(devFile, 'utf8');
    const m = src.match(new RegExp(key + ":\\s*\\n?\\s*'([^']+)'"));
    return m ? m[1] : fallback;
  } catch {
    return fallback;
  }
}

const apiBaseUrl = (process.env.API_BASE_URL || fromDev('apiBaseUrl', 'http://localhost:3001')).replace(/\/+$/, '');
const supabaseUrl = process.env.SUPABASE_URL || fromDev('supabaseUrl', '');
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || fromDev('supabaseAnonKey', '');

const contents = `/**
 * Production environment — GENERATED by scripts/set-env.js. Do not edit by hand.
 */
export const environment = {
  production: true,
  apiBaseUrl: '${apiBaseUrl}',
  supabaseUrl: '${supabaseUrl}',
  supabaseAnonKey:
    '${supabaseAnonKey}',
};
`;

fs.writeFileSync(prodFile, contents);
console.log(`[set-env] wrote environment.prod.ts (apiBaseUrl=${apiBaseUrl})`);
